// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ryuhrlisobixmeamlujm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ5dWhybGlzb2JpeG1lYW1sdWptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwNjE2NzMsImV4cCI6MjA1OTYzNzY3M30.daJnU-C4OCLMCjueQTEAvIr54zzI3WJMDKLlhMn2D6k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);